### ISSUE TITLE
L'accès SSH ne fonctionne pas en docker

### ISSUE THREAD

**Issue by mistic100** [ARIG-Robotique/robots-reader#48]

**Comment by gdepuille** [comment]
@mistic100 Qu'est-ce qui ne fonctionne pas chez toi ? 
Car je n'ai plus de soucis et je ne me sers que des versions docker.

Est-ce que tu es bien a jour sur `robot-tools` car j'ai fait des modif pour justement exposer les DNS des robots depuis le fichier hosts local lors de la création du container l'an dernier.

**Comment by gdepuille** [comment]
Le commit en question : https://github.com/ARIG-Robotique/docker-robot-tools/commit/02f3a7ac722b7db49d31667206451fe877c8cf44

**Comment by mistic100** [comment]
Abus de langage, je voulais parler de l'utilisation de la clef SSH, le but étant de ne pas avoir à configurer le mot de passe pour #49

**Comment by gdepuille** [comment]
Ça Duy avait essayé en 2019, et on était revenu en arrière car de mémoire il y avait plusieurs point qui déconnait entre le process node, et le process de copie.

A l'occaz j'y jeterai un oeil de nouveau.

**Comment by mistic100** [comment]
https://medium.com/trabe/use-your-local-ssh-keys-inside-a-docker-container-ea1d117515dc > Docker secrets to the rescue

https://docs.docker.com/engine/swarm/secrets/ Fonctionne aussi avec docker compose

**Comment by mistic100** [comment]
https://stackoverflow.com/a/54526131 > SSH agent solution

**Comment by mistic100** [comment]
```yml
    volumes:
      - $SSH_AUTH_SOCK:/ssh-agent
    environment:
      SSH_AUTH_SOCK: /ssh-agent
```

testé depuis une image fedora
```
docker run -it -v $SSH_AUTH_SOCK:/ssh-agent -e SSH_AUTH_SOCK=/ssh-agent fedora sh
```

puis clone d'un de mes dépots privé
```
GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git clone ......
```

ça fonctionne
