### ISSUE TITLE
Mettre en dur les robots

### ISSUE THREAD

**Issue by mistic100** [ARIG-Robotique/robots-reader#49]
Nerell simu est toujours sur `127.0.0.1:8080`  
Odin simu est toujours sur `127.0.0.1:8081`  

Les IP des vrais robots sont dans le fichiers hosts, ou juste y accèder par nom. Necessite de traiter #48

**Comment by gdepuille** [comment]
En ce qui me concerne c'est ce que je configure :

Simulateur :
![image](https://user-images.githubusercontent.com/775170/166157614-142248d9-b438-4d6e-abf2-7acb1fc42922.png)

Réel :
![image](https://user-images.githubusercontent.com/775170/166157630-34662d8d-12ef-4945-99e3-de4ff608860a.png)
